name = "PrimeAttention"
uuid = "8947be7e-a623-4b33-ad81-c67fb9ad3345"
version = "0.1.0"
authors = ["Jihyung Kim <awesomepeoplefund@gmail.com"]

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.11.0"
Flux = "0.16.5"
LinearAlgebra = "1.11.0"
Primes = "0.5.7"
Statistics = "1.11.0"
Zygote = "0.7.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
