name = "PrimeAttention"
uuid = "8947be7e-a623-4b33-ad81-c67fb9ad3345"
authors = ["Jihyung Kim"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
